const observer = new IntersectionObserver(
  entries => {
    entries.forEach(entry => {
      if (entry.isIntersecting) {
        entry.target.classList.add("show");
      }
    });
  },
  { threshold: 0.14 }
);

document
  .querySelectorAll(".glass-card, .feature-card, .workflow-step, .price-card, .trust-grid div, .proof-box div, .faq-list details, .lead-form, .launch-offer, .pricing-note, .pricing-intro, .plan-ideal, .risk-remover, .roi-hint, .example-scenario")
  .forEach(el => {
    el.style.opacity = "0";
    el.style.transform = "translateY(18px)";
    el.style.transition = "0.55s ease";
    observer.observe(el);
  });

const style = document.createElement("style");
style.innerHTML = `
  .show {
    opacity: 1 !important;
    transform: translateY(0) !important;
  }
`;
document.head.appendChild(style);

const translations = {
  en: {
    navProblems: "Problems",
    navSolution: "Solution",
    navPricing: "Pricing",
    navDemo: "Demo",
    eyebrow: "Built for high-volume aesthetic, dental & medical tourism clinics",
    heroTitle: "Turn WhatsApp messages into booked patients — before they go to another clinic.",
    heroSubtitle: "Most clinics lose patients because they reply too late. ConveXa replies instantly, qualifies patients, and guides them to booking.",
    tryDemo: "See how clinics turn messages into bookings",
    talkWhatsapp: "Get your clinic setup",
    trustResponse: "response feel",
    trustIntake: "patient intake",
    trustReady: "Clinic-ready",
    trustLanguages: "structured patient flows",
    assistantName: "ConveXa AI Receptionist",
    onlineNow: "online now",
    chat1: "Hello 👋 Which treatment are you interested in?",
    chat2: "Dental implants",
    chat3: "Great. Are you looking for a consultation this week?",
    chat4: "Yes, preferably tomorrow",
    chat5: "We have 2:00 PM and 5:30 PM available. Which works best?",
    float1Title: "Qualified lead",
    float1Text: "Service + preferred time collected",
    float2Title: "Booking intent detected",
    float2Text: "Patient guided automatically",

    beforeAfterLabel: "Before / After",
    beforeAfterTitle: "See the difference in the patient journey.",
    beforeAfterText: "ConveXa turns missed conversations into structured booking requests.",
    beforeTitle: "Before ConveXa",
    before1: "Patient asks",
    before2: "Clinic replies after hours",
    before3: "Patient disappears",
    afterTitle: "After ConveXa",
    after1: "Instant reply",
    after2: "Guided conversation",
    after3: "Booking request collected",

    problemLabel: "The problem",
    problemTitle: "Your next patient should not wait for a reply.",
    problemText: "Clinics lose high-intent patients when WhatsApp becomes messy, slow, and unstructured. Every delayed reply is a lost patient. Patients don’t wait. They message the next clinic.",
    problem1Title: "Slow replies",
    problem1Text: "Patients compare clinics fast. Delayed replies turn warm leads into lost revenue.",
    problem2Title: "Message overload",
    problem2Text: "Your team repeats the same answers while important inquiries get buried.",
    problem3Title: "After-hours loss",
    problem3Text: "Night and weekend messages often disappear before your team can respond.",
    problem4Title: "No intake structure",
    problem4Text: "Missing service, date, budget, or contact details makes follow-up slower.",

    solutionLabel: "The solution",
    solutionTitle: "A WhatsApp AI receptionist designed to convert patients.",
    solutionText: "ConveXa is not a basic auto-reply. It is a patient conversion engine that guides patients through a structured conversation until they are ready to book.",
    step1Title: "Understand intent",
    step1Text: "Detects whether the patient wants prices, services, availability, or booking.",
    step2Title: "Ask follow-up questions",
    step2Text: "Collects treatment interest, preferred day, time, name, and phone.",
    step3Title: "Guide toward appointment",
    step3Text: "Turns loose conversations into structured booking requests.",
    step4Title: "Handoff when needed",
    step4Text: "Complex cases can be escalated to your team with context already collected.",

    proof1Title: "+3x faster response time",
    proof1Text: "Patients get answers while they are still interested.",
    proof2Title: "+2x more booking requests",
    proof2Text: "Structured flows push conversations toward action.",
    proof3Title: "24/7 patient handling",
    proof3Text: "Night, weekend, and peak-hour inquiries keep moving.",

    howLabel: "How it works",
    howTitle: "How it works in your clinic.",
    how1Title: "Connect WhatsApp",
    how1Text: "Start from the channel your patients already use every day.",
    how2Title: "Set your services",
    how2Text: "Build flows around treatments, prices, availability, and handoff rules.",
    how3Title: "Receive qualified booking requests",
    how3Text: "Your team gets clearer requests with patient details already collected.",

    intelLabel: "Patient conversion engine",
    intelTitle: "Built to sell the appointment, not just answer messages.",
    intel1Title: "Service-aware conversations",
    intel1Text: "Dental implants, whitening, fillers, hair transplant consultation, medical tourism requests — each flow can be structured differently.",
    intel2Title: "Booking-first logic",
    intel2Text: "The AI receptionist keeps the patient moving forward: service → day → time → name → phone → confirmation.",
    intel3Title: "Multilingual-ready",
    intel3Text: "The website is available in English, Arabic, and Turkish, while system language support can expand based on clinic needs.",

    trustLabel: "Trust",
    trustTitle: "Designed for real clinic environments.",
    trust1Title: "Responds in seconds",
    trust1Text: "Fast replies when patients are still interested.",
    trust2Title: "Built for real workflows",
    trust2Text: "Questions, services, timing, contact details, and handoff.",
    trust3Title: "High-conversion conversations",
    trust3Text: "Structured to move patients toward confirmed appointments.",
    trust4Title: "Website in 3 languages",
    trust4Text: "English, Arabic, and Turkish experience for clinic owners.",

    whoLabel: "Who is this for",
    whoTitle: "Built for clinics where every inquiry can become revenue.",
    who1Title: "Aesthetic clinics",
    who1Text: "Botox, fillers, skin treatments, and consultation requests.",
    who2Title: "Dental clinics",
    who2Text: "Implants, veneers, whitening, smile design, and consultations.",
    who3Title: "Medical tourism clinics",
    who3Text: "Treatment interest, travel timing, languages, and qualified requests.",

    pricingLabel: "Pricing",
    pricingTitle: "Start simple. Upgrade when your clinic needs more intelligence.",
    pricingSubtitle: "Turn WhatsApp conversations into real booked patients — automatically.",
    launchOffer: "Limited launch offer: setup fee waived for annual plans.",
    pricingIntro: "Clinics using ConveXa typically respond faster and convert more WhatsApp inquiries into bookings.",
    pricingNote: "Setup fee is paid once. Monthly fee covers hosting, maintenance, improvements, and support.",
    riskRemover: "If you don’t see improvement in patient response and booking flow, we’ll optimize it for free.",

    basicPlan: "Basic",
    basicPrice: "$149 <small>/ month</small>",
    basicSetup: "$300 one-time setup",
    basicText: "Stop losing ready-to-book patients — just because you replied late.",
    basicIdeal: "Ideal for clinics with low message volume",
    basic1: "Automated WhatsApp replies",
    basic2: "FAQ handling",
    basic3: "Basic booking flow",
    basic4: "Collect name, phone, service, preferred time",
    basic5: "1 language",
    basic6: "Up to 1 clinic branch",
    basic7: "Basic support",
    startBasic: "Get Started",

    popular: "🔥 Best for growing clinics",
    proPlan: "Pro",
    proPrice: "$499 <small>/ month</small>",
    proSetup: "$1,000 one-time setup",
    proText: "Turn daily WhatsApp inquiries into actual booked patients — automatically.",
    proIdeal: "Ideal for clinics receiving daily inquiries",
    proRoi: "Just 1–2 extra bookings per week can pay for this plan.",
    pro1: "Everything in Basic",
    pro2: "Advanced patient qualification",
    pro3: "Service-based flows",
    pro4: "Price inquiry handling",
    pro5: "Booking-intent detection",
    pro6: "Human handoff rules",
    pro7: "Multi-language flow structure",
    pro8: "Monthly optimization",
    pro9: "Up to 3 clinic branches",
    discussPro: "See How It Works",

    customPlan: "Custom",
    customPrice: "Starting at $1,000 <small>/ month</small>",
    customSetup: "Custom one-time setup",
    customText: "Built for clinics where every missed message = lost revenue",
    customIdeal: "Ideal for high-volume clinics & medical tourism",
    custom1: "Fully custom automation system",
    custom2: "Multi-branch workflows",
    custom3: "Advanced integrations",
    custom4: "CRM / Google Sheets / calendar connection",
    custom5: "Custom reporting",
    custom6: "Custom handoff logic",
    custom7: "Priority support",
    custom8: "Full patient journey design",
    buildCustom: "Build Custom System",

    exampleLabel: "Example scenario",
    exampleTitle: "Clinic receives 50+ messages/day",
    exampleText: "AI handles them, qualifies patients, and organizes booking requests automatically.",

    leadLabel: "Get started",
    leadTitle: "Get your clinic setup",
    leadText: "Send your clinic details and we will help you set up your WhatsApp booking system.",
    clinicName: "Clinic name",
    country: "Country",
    whatsapp: "WhatsApp",
    submitLead: "Submit",

    faqLabel: "FAQ",
    faqTitle: "Questions clinics ask before starting.",
    faq1Q: "Does this work with WhatsApp Business?",
    faq1A: "Yes. ConveXa is built around WhatsApp-first clinic workflows.",
    faq2Q: "Can I customize flows?",
    faq2A: "Yes. Flows can be customized by service, clinic type, language, and booking process.",
    faq3Q: "What if the patient asks something complex?",
    faq3A: "Complex cases can be handed off to your team with the patient context already collected.",
    faq4Q: "How long does setup take?",
    faq4A: "Setup depends on your services and flows, but the system is designed to launch quickly.",
    faq5Q: "Does it support multiple languages?",
    faq5A: "Yes. The website supports English, Arabic, and Turkish, and patient flows can be expanded based on clinic needs.",

    startWithConvexa: "Start with ConveXa",
    finalTitle: "Your next patient is already messaging you.",
    finalText: "The only question is: who replies first?",
    continueWhatsapp: "Get your clinic set up in 24–48 hours"
  },

  ar: {
    navProblems: "المشاكل",
    navSolution: "الحل",
    navPricing: "الأسعار",
    navDemo: "الديمو",
    eyebrow: "مصمم للعيادات عالية الطلب: التجميل، الأسنان، والسياحة العلاجية",
    heroTitle: "حوّل رسائل واتساب إلى مرضى محجوزين — قبل أن يذهبوا إلى عيادة أخرى.",
    heroSubtitle: "معظم العيادات تخسر المرضى لأنها ترد متأخرة. ConveXa يرد فوراً، يؤهل المرضى، ويوجههم نحو الحجز.",
    tryDemo: "شاهد كيف تحوّل العيادات الرسائل إلى حجوزات",
    talkWhatsapp: "جهّز عيادتك",
    trustResponse: "استجابة سريعة",
    trustIntake: "استقبال المرضى",
    trustReady: "جاهز للعيادات",
    trustLanguages: "مسارات مرضى منظمة",
    assistantName: "موظف استقبال ConveXa الذكي",
    onlineNow: "متصل الآن",
    chat1: "مرحباً 👋 ما العلاج الذي تهتم به؟",
    chat2: "زراعة الأسنان",
    chat3: "رائع. هل ترغب باستشارة هذا الأسبوع؟",
    chat4: "نعم، يفضل غداً",
    chat5: "لدينا 2:00 مساءً أو 5:30 مساءً. أي وقت يناسبك؟",
    float1Title: "عميل مؤهل",
    float1Text: "تم جمع الخدمة والوقت المفضل",
    float2Title: "نية حجز واضحة",
    float2Text: "تم توجيه المريض تلقائياً",

    beforeAfterLabel: "قبل / بعد",
    beforeAfterTitle: "شاهد الفرق في رحلة المريض.",
    beforeAfterText: "ConveXa يحوّل المحادثات الضائعة إلى طلبات حجز منظمة.",
    beforeTitle: "قبل ConveXa",
    before1: "المريض يسأل",
    before2: "العيادة ترد بعد ساعات",
    before3: "المريض يختفي",
    afterTitle: "بعد ConveXa",
    after1: "رد فوري",
    after2: "محادثة موجهة",
    after3: "تم جمع طلب الحجز",

    problemLabel: "المشكلة",
    problemTitle: "مريضك القادم لا يجب أن ينتظر الرد.",
    problemText: "العيادات تخسر مرضى جاهزين عندما يصبح واتساب بطيئاً وغير منظم. كل رد متأخر يعني مريضاً ضائعاً. المرضى لا ينتظرون، بل يراسلون العيادة التالية.",
    problem1Title: "ردود بطيئة",
    problem1Text: "المرضى يقارنون بسرعة. التأخير يحول الفرص الجاهزة إلى خسارة.",
    problem2Title: "ضغط الرسائل",
    problem2Text: "فريقك يكرر نفس الردود بينما تضيع الرسائل المهمة.",
    problem3Title: "خسارة خارج الدوام",
    problem3Text: "رسائل الليل ونهاية الأسبوع تضيع قبل أن يرد الفريق.",
    problem4Title: "لا يوجد تنظيم للاستقبال",
    problem4Text: "غياب الخدمة أو التاريخ أو بيانات التواصل يجعل المتابعة أبطأ.",

    solutionLabel: "الحل",
    solutionTitle: "موظف استقبال ذكي على واتساب مصمم لتحويل المرضى.",
    solutionText: "ConveXa ليس رداً تلقائياً بسيطاً. إنه محرك تحويل للمرضى يقودهم داخل محادثة منظمة حتى يصبحوا جاهزين للحجز.",
    step1Title: "فهم نية المريض",
    step1Text: "يعرف إن كان المريض يسأل عن الأسعار أو الخدمات أو المواعيد أو الحجز.",
    step2Title: "طرح أسئلة متابعة",
    step2Text: "يجمع الخدمة المطلوبة، اليوم، الوقت، الاسم، ورقم الهاتف.",
    step3Title: "التوجيه نحو الحجز",
    step3Text: "يحوّل المحادثات العشوائية إلى طلبات حجز منظمة.",
    step4Title: "تحويل للبشر عند الحاجة",
    step4Text: "الحالات المعقدة يمكن تحويلها للفريق مع كل المعلومات المهمة.",

    proof1Title: "+3x سرعة استجابة أعلى",
    proof1Text: "المرضى يحصلون على الرد وهم ما زالوا مهتمين.",
    proof2Title: "+2x طلبات حجز أكثر",
    proof2Text: "المسارات المنظمة تدفع المحادثات نحو خطوة واضحة.",
    proof3Title: "تعامل مع المرضى 24/7",
    proof3Text: "رسائل الليل ونهاية الأسبوع وأوقات الضغط تبقى مستمرة.",

    howLabel: "كيف يعمل",
    howTitle: "كيف يعمل داخل عيادتك.",
    how1Title: "اربط واتساب",
    how1Text: "ابدأ من القناة التي يستخدمها مرضاك يومياً.",
    how2Title: "حدد خدماتك",
    how2Text: "ابنِ مسارات حول العلاجات، الأسعار، التوفر، وقواعد التحويل للفريق.",
    how3Title: "استقبل طلبات حجز مؤهلة",
    how3Text: "فريقك يستلم طلبات أوضح مع بيانات المريض جاهزة.",

    intelLabel: "محرك تحويل المرضى",
    intelTitle: "مصمم لبيع الموعد، وليس فقط الرد على الرسائل.",
    intel1Title: "محادثات حسب الخدمة",
    intel1Text: "زراعة الأسنان، التبييض، الفيلر، استشارة زراعة الشعر، والسياحة العلاجية — كل مسار يمكن تنظيمه حسب الحاجة.",
    intel2Title: "منطق يركز على الحجز",
    intel2Text: "موظف الاستقبال الذكي يحرك المريض خطوة بخطوة: الخدمة → اليوم → الوقت → الاسم → الهاتف → التأكيد.",
    intel3Title: "جاهز لعدة لغات",
    intel3Text: "الموقع متاح بالإنجليزية والعربية والتركية، ودعم لغات النظام يمكن توسيعه حسب احتياج العيادة.",

    trustLabel: "الثقة",
    trustTitle: "مصمم لبيئة العيادات الحقيقية.",
    trust1Title: "يرد خلال ثوانٍ",
    trust1Text: "رد سريع عندما يكون المريض ما زال مهتماً.",
    trust2Title: "مبني على سير عمل واقعي",
    trust2Text: "أسئلة، خدمات، توقيت، بيانات تواصل، وتحويل للفريق.",
    trust3Title: "محادثات عالية التحويل",
    trust3Text: "منظمة لدفع المرضى نحو حجز موعد.",
    trust4Title: "الموقع بثلاث لغات",
    trust4Text: "تجربة عربية وإنجليزية وتركية لأصحاب العيادات.",

    whoLabel: "لمن هذا النظام",
    whoTitle: "مصمم للعيادات التي يمكن أن يتحول فيها كل استفسار إلى إيراد.",
    who1Title: "عيادات التجميل",
    who1Text: "بوتوكس، فيلر، علاجات البشرة، وطلبات الاستشارة.",
    who2Title: "عيادات الأسنان",
    who2Text: "زراعة، فينير، تبييض، تصميم ابتسامة، واستشارات.",
    who3Title: "عيادات السياحة العلاجية",
    who3Text: "نوع العلاج، موعد السفر، اللغة، وطلبات مؤهلة.",

    pricingLabel: "الأسعار",
    pricingTitle: "ابدأ ببساطة، وطور عندما تحتاج عيادتك إلى ذكاء أكبر.",
    pricingSubtitle: "حوّل محادثات واتساب إلى مرضى محجوزين فعلياً — تلقائياً.",
    launchOffer: "عرض الإطلاق المحدود: إلغاء رسوم الإعداد عند الدفع السنوي.",
    pricingIntro: "العيادات التي تستخدم ConveXa ترد أسرع عادةً وتحول المزيد من استفسارات واتساب إلى حجوزات.",
    pricingNote: "رسوم الإعداد تُدفع مرة واحدة فقط. الاشتراك الشهري يشمل التشغيل، الصيانة، التحسينات، والدعم.",
    riskRemover: "إذا لم تلاحظ تحسناً في سرعة الرد ومسار الحجز، سنقوم بتحسين النظام مجاناً.",

    basicPlan: "Basic",
    basicPrice: "$149 <small>/ شهرياً</small>",
    basicSetup: "$300 رسوم إعداد مرة واحدة",
    basicText: "توقف عن خسارة المرضى الجاهزين للحجز فقط لأنك رددت متأخراً.",
    basicIdeal: "مناسب للعيادات ذات حجم الرسائل المنخفض",
    basic1: "ردود واتساب تلقائية",
    basic2: "التعامل مع الأسئلة الشائعة",
    basic3: "مسار حجز أساسي",
    basic4: "جمع الاسم، الهاتف، الخدمة، والوقت المفضل",
    basic5: "لغة واحدة",
    basic6: "حتى فرع عيادة واحد",
    basic7: "دعم أساسي",
    startBasic: "ابدأ الآن",

    popular: "🔥 الأفضل للعيادات النامية",
    proPlan: "Pro",
    proPrice: "$499 <small>/ شهرياً</small>",
    proSetup: "$1,000 رسوم إعداد مرة واحدة",
    proText: "حوّل استفسارات واتساب اليومية إلى مرضى محجوزين فعلياً — تلقائياً.",
    proIdeal: "مناسب للعيادات التي تستقبل استفسارات يومية",
    proRoi: "فقط حجز أو حجزان إضافيان أسبوعياً يمكن أن يدفعا تكلفة هذه الخطة.",
    pro1: "كل ما في Basic",
    pro2: "تأهيل متقدم للمرضى",
    pro3: "مسارات حسب الخدمة",
    pro4: "التعامل مع استفسارات الأسعار",
    pro5: "اكتشاف نية الحجز",
    pro6: "قواعد تحويل للبشر",
    pro7: "هيكل مسارات متعدد اللغات",
    pro8: "تحسين شهري",
    pro9: "حتى 3 فروع للعيادة",
    discussPro: "شاهد كيف يعمل",

    customPlan: "Custom",
    customPrice: "يبدأ من $1,000 <small>/ شهرياً</small>",
    customSetup: "رسوم إعداد مخصصة مرة واحدة",
    customText: "مصمم للعيادات التي تعني فيها كل رسالة فائتة خسارة إيراد.",
    customIdeal: "مناسب للعيادات عالية الطلب والسياحة العلاجية",
    custom1: "نظام أتمتة مخصص بالكامل",
    custom2: "مسارات عمل متعددة الفروع",
    custom3: "تكاملات متقدمة",
    custom4: "ربط CRM / Google Sheets / التقويم",
    custom5: "تقارير مخصصة",
    custom6: "منطق تحويل مخصص",
    custom7: "دعم أولوية",
    custom8: "تصميم كامل لرحلة المريض",
    buildCustom: "ابنِ نظاماً مخصصاً",

    exampleLabel: "سيناريو مثال",
    exampleTitle: "العيادة تستقبل أكثر من 50 رسالة يومياً",
    exampleText: "الذكاء الاصطناعي يتعامل معها، يؤهل المرضى، وينظم طلبات الحجز تلقائياً.",

    leadLabel: "ابدأ الآن",
    leadTitle: "جهّز عيادتك",
    leadText: "أرسل بيانات عيادتك وسنساعدك في إعداد نظام حجز واتساب.",
    clinicName: "اسم العيادة",
    country: "الدولة",
    whatsapp: "واتساب",
    submitLead: "إرسال",

    faqLabel: "الأسئلة الشائعة",
    faqTitle: "أسئلة تسألها العيادات قبل البدء.",
    faq1Q: "هل يعمل مع WhatsApp Business؟",
    faq1A: "نعم. ConveXa مبني حول سير عمل العيادات على واتساب.",
    faq2Q: "هل يمكنني تخصيص المسارات؟",
    faq2A: "نعم. يمكن تخصيص المسارات حسب الخدمة، نوع العيادة، اللغة، وطريقة الحجز.",
    faq3Q: "ماذا لو سأل المريض سؤالاً معقداً؟",
    faq3A: "يمكن تحويل الحالات المعقدة إلى فريقك مع كل سياق المريض المجموع مسبقاً.",
    faq4Q: "كم يستغرق الإعداد؟",
    faq4A: "يعتمد الإعداد على خدماتك ومساراتك، لكن النظام مصمم للانطلاق بسرعة.",
    faq5Q: "هل يدعم عدة لغات؟",
    faq5A: "نعم. الموقع يدعم الإنجليزية والعربية والتركية، ويمكن توسيع مسارات المرضى حسب حاجة العيادة.",

    startWithConvexa: "ابدأ مع ConveXa",
    finalTitle: "مريضك القادم يراسلك الآن.",
    finalText: "السؤال الوحيد هو: من يرد أولاً؟",
    continueWhatsapp: "جهّز عيادتك خلال 24–48 ساعة"
  },

  tr: {
    navProblems: "Sorunlar",
    navSolution: "Çözüm",
    navPricing: "Fiyatlar",
    navDemo: "Demo",
    eyebrow: "Yoğun estetik, diş ve medikal turizm klinikleri için tasarlandı",
    heroTitle: "WhatsApp mesajlarını randevulu hastalara dönüştürün — başka kliniğe gitmeden önce.",
    heroSubtitle: "Çoğu klinik geç yanıt verdiği için hasta kaybeder. ConveXa anında yanıt verir, hastaları nitelendirir ve randevuya yönlendirir.",
    tryDemo: "Kliniklerin mesajları randevuya nasıl çevirdiğini gör",
    talkWhatsapp: "Kliniğinizi kurdurun",
    trustResponse: "yanıt hissi",
    trustIntake: "hasta kabulü",
    trustReady: "Kliniklere hazır",
    trustLanguages: "hasta akışları",
    assistantName: "ConveXa AI Resepsiyonisti",
    onlineNow: "şu an çevrimiçi",
    chat1: "Merhaba 👋 Hangi tedaviyle ilgileniyorsunuz?",
    chat2: "Diş implantı",
    chat3: "Harika. Bu hafta danışmanlık ister misiniz?",
    chat4: "Evet, tercihen yarın",
    chat5: "2:00 ve 5:30 uygun. Hangisi sizin için iyi?",
    float1Title: "Nitelikli aday",
    float1Text: "Hizmet ve tercih edilen saat toplandı",
    float2Title: "Randevu niyeti algılandı",
    float2Text: "Hasta otomatik yönlendirildi",

    beforeAfterLabel: "Önce / Sonra",
    beforeAfterTitle: "Hasta yolculuğundaki farkı görün.",
    beforeAfterText: "ConveXa kaçırılan konuşmaları yapılandırılmış randevu taleplerine dönüştürür.",
    beforeTitle: "ConveXa Öncesi",
    before1: "Hasta soru sorar",
    before2: "Klinik saatler sonra yanıt verir",
    before3: "Hasta kaybolur",
    afterTitle: "ConveXa Sonrası",
    after1: "Anında yanıt",
    after2: "Yönlendirilmiş konuşma",
    after3: "Randevu talebi toplandı",

    problemLabel: "Sorun",
    problemTitle: "Bir sonraki hastanız yanıt beklememeli.",
    problemText: "WhatsApp yavaş ve dağınık olduğunda klinikler yüksek niyetli hastaları kaybeder. Her geciken yanıt kaybedilen bir hastadır. Hastalar beklemez, sonraki kliniğe yazar.",
    problem1Title: "Yavaş yanıtlar",
    problem1Text: "Hastalar hızlı karşılaştırır. Geciken yanıtlar sıcak fırsatları kayba çevirir.",
    problem2Title: "Mesaj yoğunluğu",
    problem2Text: "Ekibiniz aynı cevapları tekrar ederken önemli talepler kaybolur.",
    problem3Title: "Mesai dışı kayıp",
    problem3Text: "Gece ve hafta sonu mesajları çoğu zaman yanıtlanmadan kaybolur.",
    problem4Title: "Düzensiz hasta alımı",
    problem4Text: "Hizmet, tarih veya iletişim bilgileri eksikse takip yavaşlar.",

    solutionLabel: "Çözüm",
    solutionTitle: "Hastaları dönüştürmek için tasarlanmış WhatsApp AI resepsiyonisti.",
    solutionText: "ConveXa basit bir otomatik yanıt değildir. Hastaları randevuya hazır olana kadar yapılandırılmış bir konuşmada yönlendiren hasta dönüşüm motorudur.",
    step1Title: "Niyeti anlar",
    step1Text: "Hastanın fiyat, hizmet, uygunluk veya randevu istediğini algılar.",
    step2Title: "Takip soruları sorar",
    step2Text: "Tedavi, tercih edilen gün, saat, isim ve telefon bilgisini toplar.",
    step3Title: "Randevuya yönlendirir",
    step3Text: "Dağınık konuşmaları düzenli randevu taleplerine dönüştürür.",
    step4Title: "Gerektiğinde ekibe aktarır",
    step4Text: "Karmaşık durumlar toplanan bağlamla ekibe aktarılabilir.",

    proof1Title: "+3x daha hızlı yanıt",
    proof1Text: "Hastalar hâlâ ilgiliyken cevap alır.",
    proof2Title: "+2x daha fazla randevu talebi",
    proof2Text: "Yapılandırılmış akışlar konuşmaları aksiyona taşır.",
    proof3Title: "7/24 hasta yönetimi",
    proof3Text: "Gece, hafta sonu ve yoğun saat talepleri ilerlemeye devam eder.",

    howLabel: "Nasıl çalışır",
    howTitle: "Kliniğinizde nasıl çalışır.",
    how1Title: "WhatsApp’ı bağlayın",
    how1Text: "Hastalarınızın her gün kullandığı kanaldan başlayın.",
    how2Title: "Hizmetlerinizi ayarlayın",
    how2Text: "Tedaviler, fiyatlar, uygunluk ve aktarım kuralları etrafında akışlar oluşturun.",
    how3Title: "Nitelikli randevu talepleri alın",
    how3Text: "Ekibiniz hasta bilgileri toplanmış daha net talepler alır.",

    intelLabel: "Hasta dönüşüm motoru",
    intelTitle: "Sadece cevaplamak için değil, randevu almak için tasarlandı.",
    intel1Title: "Hizmete özel konuşmalar",
    intel1Text: "İmplant, beyazlatma, dolgu, saç ekimi danışmanlığı ve medikal turizm talepleri farklı akışlarla yönetilebilir.",
    intel2Title: "Randevu odaklı mantık",
    intel2Text: "AI resepsiyonist hastayı ilerletir: hizmet → gün → saat → isim → telefon → onay.",
    intel3Title: "Çok dile hazır",
    intel3Text: "Web sitesi İngilizce, Arapça ve Türkçe sunulur; sistem dil desteği kliniğin ihtiyacına göre genişletilebilir.",

    trustLabel: "Güven",
    trustTitle: "Gerçek klinik ortamları için tasarlandı.",
    trust1Title: "Saniyeler içinde yanıt",
    trust1Text: "Hasta hâlâ ilgilenirken hızlı cevap verir.",
    trust2Title: "Gerçek iş akışları",
    trust2Text: "Sorular, hizmetler, zamanlama, iletişim ve ekibe aktarım.",
    trust3Title: "Yüksek dönüşümlü konuşmalar",
    trust3Text: "Hastaları randevuya yönlendirecek şekilde yapılandırılmıştır.",
    trust4Title: "3 dilde web sitesi",
    trust4Text: "Klinik sahipleri için İngilizce, Arapça ve Türkçe deneyim.",

    whoLabel: "Kimler için",
    whoTitle: "Her talebin gelire dönüşebileceği klinikler için tasarlandı.",
    who1Title: "Estetik klinikleri",
    who1Text: "Botoks, dolgu, cilt tedavileri ve danışmanlık talepleri.",
    who2Title: "Diş klinikleri",
    who2Text: "İmplant, veneer, beyazlatma, gülüş tasarımı ve danışmanlıklar.",
    who3Title: "Medikal turizm klinikleri",
    who3Text: "Tedavi ilgisi, seyahat zamanı, diller ve nitelikli talepler.",

    pricingLabel: "Fiyatlandırma",
    pricingTitle: "Basit başlayın. Kliniğiniz daha fazla zekaya ihtiyaç duyduğunda yükseltin.",
    pricingSubtitle: "WhatsApp konuşmalarını gerçek randevulu hastalara otomatik olarak dönüştürün.",
    launchOffer: "Sınırlı lansman teklifi: yıllık planlarda kurulum ücreti alınmaz.",
    pricingIntro: "ConveXa kullanan klinikler genellikle daha hızlı yanıt verir ve daha fazla WhatsApp talebini randevuya dönüştürür.",
    pricingNote: "Kurulum ücreti yalnızca bir kez ödenir. Aylık ücret barındırma, bakım, iyileştirmeler ve desteği kapsar.",
    riskRemover: "Hasta yanıtı ve randevu akışında iyileşme görmezseniz, sistemi ücretsiz optimize ederiz.",

    basicPlan: "Basic",
    basicPrice: "$149 <small>/ ay</small>",
    basicSetup: "$300 tek seferlik kurulum",
    basicText: "Sırf geç yanıt verdiğiniz için randevuya hazır hastaları kaybetmeyi durdurun.",
    basicIdeal: "Düşük mesaj hacmine sahip klinikler için ideal",
    basic1: "Otomatik WhatsApp yanıtları",
    basic2: "SSS yönetimi",
    basic3: "Temel randevu akışı",
    basic4: "İsim, telefon, hizmet ve tercih edilen saat toplama",
    basic5: "1 dil",
    basic6: "En fazla 1 klinik şubesi",
    basic7: "Temel destek",
    startBasic: "Başlayın",

    popular: "🔥 Büyüyen klinikler için en iyisi",
    proPlan: "Pro",
    proPrice: "$499 <small>/ ay</small>",
    proSetup: "$1,000 tek seferlik kurulum",
    proText: "Günlük WhatsApp taleplerini otomatik olarak gerçek randevulu hastalara dönüştürün.",
    proIdeal: "Günlük talep alan klinikler için ideal",
    proRoi: "Haftada sadece 1–2 ekstra randevu bu planın maliyetini karşılayabilir.",
    pro1: "Basic içindeki her şey",
    pro2: "Gelişmiş hasta nitelendirme",
    pro3: "Hizmet bazlı akışlar",
    pro4: "Fiyat sorgusu yönetimi",
    pro5: "Randevu niyeti algılama",
    pro6: "İnsan ekibe aktarım kuralları",
    pro7: "Çok dilli akış yapısı",
    pro8: "Aylık optimizasyon",
    pro9: "En fazla 3 klinik şubesi",
    discussPro: "Nasıl çalıştığını görün",

    customPlan: "Custom",
    customPrice: "$1,000’dan başlayan <small>/ ay</small>",
    customSetup: "Özel tek seferlik kurulum",
    customText: "Her kaçırılan mesajın gelir kaybı anlamına geldiği klinikler için tasarlandı.",
    customIdeal: "Yüksek hacimli klinikler ve medikal turizm için ideal",
    custom1: "Tamamen özel otomasyon sistemi",
    custom2: "Çok şubeli iş akışları",
    custom3: "Gelişmiş entegrasyonlar",
    custom4: "CRM / Google Sheets / takvim bağlantısı",
    custom5: "Özel raporlama",
    custom6: "Özel aktarım mantığı",
    custom7: "Öncelikli destek",
    custom8: "Tam hasta yolculuğu tasarımı",
    buildCustom: "Özel sistem oluştur",

    exampleLabel: "Örnek senaryo",
    exampleTitle: "Klinik günde 50+ mesaj alıyor",
    exampleText: "AI mesajları yönetir, hastaları nitelendirir ve randevu taleplerini otomatik olarak düzenler.",

    leadLabel: "Başlayın",
    leadTitle: "Kliniğinizi kurdurun",
    leadText: "Klinik bilgilerinizi gönderin, WhatsApp randevu sisteminizi kurmanıza yardımcı olalım.",
    clinicName: "Klinik adı",
    country: "Ülke",
    whatsapp: "WhatsApp",
    submitLead: "Gönder",

    faqLabel: "SSS",
    faqTitle: "Kliniklerin başlamadan önce sorduğu sorular.",
    faq1Q: "WhatsApp Business ile çalışır mı?",
    faq1A: "Evet. ConveXa, WhatsApp öncelikli klinik iş akışları için tasarlanmıştır.",
    faq2Q: "Akışları özelleştirebilir miyim?",
    faq2A: "Evet. Akışlar hizmete, klinik türüne, dile ve randevu sürecine göre özelleştirilebilir.",
    faq3Q: "Hasta karmaşık bir şey sorarsa ne olur?",
    faq3A: "Karmaşık durumlar, hasta bağlamı toplanmış şekilde ekibinize aktarılabilir.",
    faq4Q: "Kurulum ne kadar sürer?",
    faq4A: "Kurulum hizmetlerinize ve akışlarınıza bağlıdır, ancak sistem hızlı başlamak için tasarlanmıştır.",
    faq5Q: "Birden fazla dili destekler mi?",
    faq5A: "Evet. Web sitesi İngilizce, Arapça ve Türkçeyi destekler; hasta akışları klinik ihtiyacına göre genişletilebilir.",

    startWithConvexa: "ConveXa ile başla",
    finalTitle: "Bir sonraki hastanız şu anda mesaj atıyor.",
    finalText: "Tek soru şu: ilk kim yanıtlıyor?",
    continueWhatsapp: "Kliniğinizi 24–48 saat içinde kurdurun"
  }
};

function setLanguage(lang) {
  const dict = translations[lang] || translations.en;

  document.documentElement.lang = lang;
  document.body.classList.toggle("rtl", lang === "ar");

  document.querySelectorAll("[data-i18n]").forEach(el => {
    const key = el.dataset.i18n;

    if (dict[key]) {
      if (key.includes("Price")) {
        el.innerHTML = dict[key];
      } else {
        el.textContent = dict[key];
      }
    }
  });

  document.querySelectorAll("[data-i18n-placeholder]").forEach(el => {
    const key = el.dataset.i18nPlaceholder;
    if (dict[key]) el.placeholder = dict[key];
  });

  document.querySelectorAll(".lang-switch button").forEach(btn => {
    btn.classList.toggle("active", btn.dataset.lang === lang);
  });

  localStorage.setItem("convexaLang", lang);
}

document.querySelectorAll(".lang-switch button").forEach(btn => {
  btn.addEventListener("click", () => setLanguage(btn.dataset.lang));
});

setLanguage(localStorage.getItem("convexaLang") || "en");